app:
  name: collagegenerator
  replicaCount: 1
  image:
    repository: collagegenerator
    tag: latest
    pullPolicy: IfNotPresent
  # Resource management
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  # Health checks
  livenessProbe:
    enabled: true
    path: /health
    port: 8080
    initialDelaySeconds: 30
    periodSeconds: 10
  readinessProbe:
    enabled: true
    path: /ready
    port: 8080
    initialDelaySeconds: 5
    periodSeconds: 10
  # Autoscaling
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
  # Ingress configuration
  ingress:
    enabled: false
    host: collagegenerator.local
    tls: false

postgresql:
  host: collage-postgresql
  port: 5432
  user: postgres
  password: postgres
  database: collage
  # PostgreSQL resource management
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

store:
  root: /data/store
  # Storage configuration
  persistence:
    enabled: true
    size: 1Gi
    storageClass: "standard"

# Feature flags
runMigrations: false